# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formentry',
            name='postedbyusername',
            field=models.CharField(default='anonymous', max_length=100, verbose_name='webmail'),
        ),
    ]
